### ISSUE TITLE
Optional bikeshedding: Explicit Fees?

### ISSUE THREAD

**Issue by bumblefudge** [decentralized-identity/did-traits#18]
(feel free to close or tag vNext, etc)

Leaving a mental note that "explicit fees" is confusing -- don't all systems have fees at some layer that are variously explicit-able? Is did:dht's "liveness"/republishing requirement an explicit fee?  On today's call JC also mentioned that this trait sticks out a little, since all the others are clearly [positive] features, while this might feel like a negative feature/detraction.  Perhaps this could use a little bikeshedding?

**Comment by ottomorac** [comment]
I agree that explicit fees is hard to measure. And plus not all did methods have a cost for did generation, credential issuance, key rotation, or credential revocation. 

A more objective trait could be: "Does DID issuance, or key rotation have a cost?" (yes / no) type question.  But even that seems to be of little value in my perspective.

**Comment by jceb** [comment]
The trait `explicitFees` has been named to `transactionalFees` to better reflect the nature of the fee.
